# Generated by Django 4.1.4 on 2022-12-26 05:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_categories_ouds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouds',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
