# Generated by Django 4.1.4 on 2022-12-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_alter_ouds_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouds',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='2.5', max_digits=10),
        ),
    ]
