# Generated by Django 4.1.4 on 2023-01-04 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_ouds_base_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.IntegerField(max_length=5)),
                ('amount1', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('amount2', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('amount3', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('amount4', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('amount5', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ouds',
            name='user',
        ),
        migrations.AlterField(
            model_name='ouds',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.categories'),
        ),
        migrations.AddField(
            model_name='ouds',
            name='amount_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.quantitymanagement'),
        ),
    ]
