# Generated by Django 4.1.4 on 2023-01-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0009_rename_amount1_quantitymanagement_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouds',
            name='amount_number',
            field=models.IntegerField(default=3, max_length=5),
        ),
    ]
