# Generated by Django 4.1.4 on 2023-01-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0010_ouds_amount_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouds',
            name='amount_number',
            field=models.IntegerField(default='3'),
        ),
    ]
