# Generated by Django 4.1.4 on 2023-01-10 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0011_alter_ouds_amount_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=5000)),
                ('progress', models.IntegerField(default='0', max_length=100)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('delivary_date', models.DateField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.order')),
            ],
        ),
    ]
