# Generated by Django 4.1.4 on 2023-01-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0012_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='delivary_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='progress',
            field=models.IntegerField(default='0'),
        ),
    ]
