# Generated by Django 4.1.4 on 2023-01-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0013_alter_tracker_delivary_date_alter_tracker_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='delivary_date',
            field=models.DateField(auto_now=True),
        ),
    ]
