# Generated by Django 4.1.4 on 2023-01-12 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0014_alter_tracker_delivary_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order1',
            field=models.JSONField(blank=True, default='{nice}', max_length=5000),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='delivary_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 1, 12)),
        ),
    ]
