# Generated by Django 4.1.4 on 2023-01-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0015_order_order1_alter_tracker_delivary_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order1',
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default='100', max_digits=30),
        ),
    ]
