# Generated by Django 4.1.4 on 2023-04-12 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0016_remove_order_order1_order_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='tracker',
            name='delivary_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 4, 12)),
        ),
    ]
