# Generated by Django 4.1.4 on 2023-04-18 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0017_contactus_alter_tracker_delivary_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouds',
            name='fake_price_1',
            field=models.DecimalField(decimal_places=2, default='000000.00', max_digits=30),
        ),
        migrations.AddField(
            model_name='ouds',
            name='fake_price_2',
            field=models.DecimalField(decimal_places=2, default='000000.00', max_digits=30),
        ),
        migrations.AddField(
            model_name='ouds',
            name='fake_price_3',
            field=models.DecimalField(decimal_places=2, default='000000.00', max_digits=30),
        ),
        migrations.AddField(
            model_name='ouds',
            name='fake_price_4',
            field=models.DecimalField(decimal_places=2, default='000000.00', max_digits=30),
        ),
        migrations.AddField(
            model_name='ouds',
            name='offer_amount',
            field=models.IntegerField(default='50'),
        ),
        migrations.AddField(
            model_name='ouds',
            name='offer_status',
            field=models.CharField(default='closed', max_length=5),
        ),
        migrations.AddField(
            model_name='ouds',
            name='price_1',
            field=models.DecimalField(decimal_places=2, default='000000.00', max_digits=30),
        ),
        migrations.AddField(
            model_name='ouds',
            name='price_2',
            field=models.DecimalField(decimal_places=2, default='000000.00', max_digits=30),
        ),
        migrations.AddField(
            model_name='ouds',
            name='price_3',
            field=models.DecimalField(decimal_places=2, default='000000.00', max_digits=30),
        ),
        migrations.AddField(
            model_name='ouds',
            name='price_4',
            field=models.DecimalField(decimal_places=2, default='000000.00', max_digits=30),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='delivary_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 4, 18)),
        ),
    ]
