# Generated by Django 4.1.4 on 2023-04-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0018_ouds_fake_price_1_ouds_fake_price_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouds',
            name='exerpt',
            field=models.CharField(default='nice', max_length=150),
        ),
        migrations.AlterField(
            model_name='ouds',
            name='description',
            field=models.CharField(max_length=3000),
        ),
    ]
