# Generated by Django 4.1.4 on 2023-05-12 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0019_ouds_exerpt_alter_ouds_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouds',
            name='offer_status',
            field=models.CharField(default='closed', max_length=10),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='delivary_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 5, 12)),
        ),
    ]
