# Generated by Django 4.1.4 on 2023-05-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0021_alter_tracker_delivary_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='user', max_length=1000),
        ),
    ]
