# Generated by Django 4.1.4 on 2023-05-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0022_user_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ouds',
            old_name='fake_price_1',
            new_name='prev_price_1',
        ),
        migrations.RenameField(
            model_name='ouds',
            old_name='fake_price_2',
            new_name='prev_price_2',
        ),
        migrations.RenameField(
            model_name='ouds',
            old_name='fake_price_3',
            new_name='prev_price_3',
        ),
        migrations.RenameField(
            model_name='ouds',
            old_name='fake_price_4',
            new_name='prev_price_4',
        ),
    ]
