# Generated by Django 4.1.4 on 2023-05-16 14:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0023_rename_fake_price_1_ouds_prev_price_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='WebContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutus', models.CharField(max_length=10000)),
                ('privacy_policy', models.CharField(max_length=10000)),
                ('payment_policy', models.CharField(max_length=10000)),
                ('shipping_policy', models.CharField(max_length=10000)),
                ('term_and_conditions', models.CharField(max_length=10000)),
                ('exchange_and_return', models.CharField(max_length=10000)),
                ('delivery_charge', models.IntegerField()),
                ('contact_no', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('featured_product_id_1', models.CharField(max_length=10)),
                ('featured_product_id_2', models.CharField(max_length=10)),
                ('featured_product_id_3', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='not delivered', max_length=20),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='delivary_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 5, 16)),
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
