# Generated by Django 4.1.4 on 2023-05-17 11:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0024_promos_webcontents_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ouds',
            name='cover_image2',
        ),
        migrations.RemoveField(
            model_name='ouds',
            name='cover_image3',
        ),
        migrations.AddField(
            model_name='ouds',
            name='tags',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='webcontents',
            name='contact_no_2',
            field=models.CharField(default='0915485', max_length=20),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='delivary_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 5, 17)),
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Moderators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
