# Generated by Django 4.1.4 on 2023-05-20 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0025_remove_ouds_cover_image2_remove_ouds_cover_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouds',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='promos',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='delivary_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 5, 20)),
        ),
    ]
