# Generated by Django 4.1.4 on 2023-05-26 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0026_ouds_visibility_alter_promos_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bios',
        ),
        migrations.AddField(
            model_name='user',
            name='contact_no',
            field=models.CharField(default='01746695655', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Raihan Rashid', max_length=1000),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='delivary_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 5, 26)),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
