# Generated by Django 4.1.4 on 2023-05-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0028_remove_user_cover_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=20),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_discount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=30),
        ),
        migrations.AddField(
            model_name='ouds',
            name='inventory',
            field=models.DecimalField(decimal_places=2, default='100.00', max_digits=30),
        ),
    ]
