# Generated by Django 4.1.4 on 2023-05-28 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0029_order_delivery_charge_order_promo_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Cash On Delivery', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_name',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='ouds',
            name='total_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='delivary_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 5, 28)),
        ),
    ]
