# Generated by Django 4.1.4 on 2023-05-29 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0030_order_payment_method_order_promo_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sale', models.IntegerField()),
                ('total_credits', models.DecimalField(decimal_places=2, max_digits=30)),
                ('total_stock', models.IntegerField()),
                ('total_orders', models.IntegerField()),
                ('total_deliveries', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='promo_name',
        ),
        migrations.AddField(
            model_name='order',
            name='area',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='town',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='area',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='town',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='delivary_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 5, 29)),
        ),
    ]
