# Generated by Django 4.1.4 on 2023-05-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0031_analytics_remove_order_promo_name_order_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
