# Generated by Django 4.1.4 on 2023-05-31 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0032_order_is_paid_user_has_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reason_for_cancellation',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='delivary_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 5, 31)),
        ),
    ]
