# Generated by Django 4.1.4 on 2023-06-01 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0033_order_reason_for_cancellation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='reason_for_cancellation',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='delivary_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 6, 1)),
        ),
    ]
