# Generated by Django 4.1.4 on 2023-06-25 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0035_user_default_shipping_id_alter_tracker_delivary_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouds',
            name='cover_image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='delivary_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 6, 25)),
        ),
    ]
