# Generated by Django 4.1.4 on 2023-06-25 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0037_noticeborad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NoticeBorad',
            new_name='NoticeBoard',
        ),
    ]
