# Generated by Django 4.1.4 on 2023-06-30 15:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0038_rename_noticeborad_noticeboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usr_name',
            field=models.CharField(default='username', max_length=100),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='delivary_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 6, 30)),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_no',
            field=models.CharField(default='01700000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.order'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
