# Generated by Django 4.1.4 on 2023-06-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0040_remove_user_usr_name_alter_user_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
