# Generated by Django 4.1.4 on 2023-07-01 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0041_alter_user_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='order_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='delivary_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 7, 1)),
        ),
    ]
