# Generated by Django 4.1.4 on 2023-07-02 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0044_user_otp_user_otp_last_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_no_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_last_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 10, 2, 10, 616527)),
        ),
    ]
