# Generated by Django 4.1.4 on 2023-07-02 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0045_user_contact_no_verified_alter_user_otp_last_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contact_no_verified',
            new_name='contact_verified',
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_last_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 10, 3, 51, 281216)),
        ),
    ]
