# Generated by Django 4.1.4 on 2023-07-02 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0046_rename_contact_no_verified_user_contact_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contact_no',
            new_name='contact',
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_last_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 10, 5, 36, 404662)),
        ),
    ]
