# Generated by Django 4.1.4 on 2023-07-02 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0044_alter_tracker_delivary_date_alter_user_contact_no'),
        ('basic', '0047_rename_contact_no_user_contact_and_more'),
    ]

    operations = [
    ]
