# Generated by Django 4.1.4 on 2023-07-02 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0049_remove_user_contact_alter_user_otp_last_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contact_no',
            new_name='contact',
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_last_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 18, 58, 0, 844147)),
        ),
    ]
