# Generated by Django 4.1.4 on 2023-07-04 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0049_remove_user_contact_no_alter_tracker_delivary_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_last_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 6, 52, 56, 900788)),
        ),
    ]
