# Generated by Django 4.1.4 on 2023-07-02 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0050_rename_contact_no_user_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_last_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 18, 58, 50, 241721)),
        ),
    ]
