# Generated by Django 4.1.4 on 2023-08-06 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0051_alter_user_otp_last_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='delivary_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 8, 6)),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_last_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 6, 8, 33, 45, 387970)),
        ),
    ]
